# -*- coding: utf-8 -*-
"""Conteúdo do Catálogo de Produtos da Paratudo.

Este arquivo é a FONTE do catálogo: pra mudar nome de linha, foto, seção ou
página, edite aqui e rode `python tools/build_simplificado.py`.

Cada linha: (nome, [fotos]) — fotos são números do acervo tools/fotos_docx/
(image{N}.png|jpeg extraídas do Word "CATALOGO PARATUDO.docx").
A PRIMEIRA foto da lista é a que aparece no catálogo; as demais ficam de reserva.
"""

# ---------------------------------------------------------------- seções
SECOES = {
 'manuais': {
  'nome': 'Ferramentas Manuais', 'icone': 'chave',
  'marcas': ['Gedore', 'Tramontina', 'Sata', 'Stanley', 'Vonder'],
  'linhas': [
   ('Chavaria em Geral', [2, 1, 3, 4, 5, 6]),
   ('Chaves com Catraca', [7]),
   ('Chaves de Fenda e Phillips', [8]),
   ('Alicates Universais', [9]),
   ('Alicates de Pressão', [10]),
   ('Alicates de Crimpar e Decapar', [11, 12]),
   ('Chaves de Tubo e Ajustáveis', [13, 14]),
   ('Soquetes e Acessórios', [16, 15, 17]),
   ('Martelos e Marretas', [18, 19, 20, 21, 22, 23]),
   ('Saca Polias', [24, 25]),
   ('Estiletes', [26, 27, 28, 29]),
   ('Trenas', [30, 31, 32]),
   ('Arcos de Serra', [33]),
   ('Tesouras Corta Vergalhão', [34]),
   ('Rebitadores', [35, 36]),
   ('Grampos Tipo C', [37]),
   ('Sargentos', [38]),
   ('Tornos de Bancada', [39]),
  ]},
 'corte': {
  'nome': 'Ferramentas de Corte', 'icone': 'serra',
  'marcas': ['Starrett', 'Cortag', 'Walter'],
  'linhas': [
   ('Machos: Máquina, Manual e Tubo', [40]),
   ('Brocas', [41]),
   ('Limas Rotativas', [42]),
   ('Cossinetes', [43]),
   ('Serras Copo', [44, 45, 46]),
   ('Serras Tico-Tico e Lâminas', [47, 48, 49, 50]),
   ('Discos de Serra Circular', [51]),
   ('Discos Diamantados', [52, 53, 54, 55, 56]),
  ]},
 'abrasivos': {
  'nome': 'Abrasivos', 'icone': 'disco',
  'marcas': ['Norton', '3M', 'Walter'],
  'linhas': [
   ('Discos de Corte', [57, 58, 59]),
   ('Discos de Desbaste', [60]),
   ('Discos Flap', [61, 62]),
   ('Discos de Lixa', [63]),
   ('Discos Pluma Hookit', [64]),
   ('Rebolos Uso Geral', [65, 66, 67]),
   ('Rebolos Tipo Copo', [68]),
   ('Folhas de Lixa', [69, 70, 71]),
   ('Rodas de Lixa', [72, 73]),
   ('Mantas Abrasivas', [74]),
   ('Pontas Montadas', [75]),
   ('Pedras Abrasivas', [79, 80, 81, 82]),
  ]},
 'bateria': {
  'nome': 'Ferramentas a Bateria', 'icone': 'bateria',
  'marcas': ['DeWalt', 'Makita', 'Black+Decker'],
  'denso': True,
  'linhas': [
   ('Chaves de Impacto', [76]),
   ('Parafusadeiras', [77]),
   ('Serras Tico-Tico', [78]),
   ('Esmerilhadeiras', [83]),
   ('Aplicadores de Silicone', [84]),
   ('Lanternas', [85]),
   ('Engraxadeiras', [86]),
   ('Marteletes e Martelos', [87, 88]),
   ('Lixadeiras', [89]),
   ('Aspiradores de Pó Portáteis', [90]),
   ('Plainas', [91]),
   ('Eletrosserras', [92]),
   ('Multioscilantes', [93]),
   ('Tupias', [94]),
   ('Sopradores Térmicos', [95]),
   ('Pinadores', [96]),
   ('Retíficas', [97]),
   ('Serras de Esquadria', [98]),
   ('Lavadoras de Alta Pressão', [99]),
   ('Lavadoras Portáteis', [100]),
   ('Roçadeiras', [101]),
   ('Sopradores', [102]),
   ('Tesouras de Chapa', [103]),
   ('Serras Sabre', [104]),
   ('Máquinas de Assentar Piso', [105]),
   ('Ventosas', [106]),
   ('Mini Compressores de Ar', [107]),
   ('Serras Circulares', [108]),
   ('Serras Mármore', [109]),
   ('Baterias e Carregadores', [110, 111]),
  ]},
 'eletricas': {
  'nome': 'Ferramentas Elétricas', 'icone': 'plugue',
  'marcas': ['DeWalt', 'Makita'],
  'linhas': [
   ('Furadeiras', [112]),
   ('Marteletes', [113]),
   ('Martelos Demolidores', [114]),
   ('Serras de Esquadria', [115]),
   ('Policortes', [116]),
   ('Politrizes', [117]),
   ('Esmerilhadeiras 4.1/2", 7" e 9"', [118]),
   ('Serras Mármore', [119]),
   ('Lixadeiras', [120, 121, 122]),
   ('Retíficas', [123]),
   ('Serras Circulares', [124]),
   ('Tupias', [125]),
   ('Plainas', [126]),
   ('Afiadores de Broca', [127]),
   ('Lixadeiras de Parede', [128]),
  ]},
 'medicao': {
  'nome': 'Medição e Teste', 'icone': 'paquimetro',
  'marcas': ['Minipa', 'Starrett'],
  'linhas': [
   ('Trenas a Laser', [129]),
   ('Níveis a Laser', [133]),
   ('Medidores de Distância', [136]),
   ('Paquímetros e Micrômetros', [155, 156, 157]),
   ('Alicates Amperímetro', [158]),
   ('Termômetros', [159, 160]),
   ('Detectores de Tensão', [161]),
   ('Pontas de Teste', [162, 163]),
  ]},
 'solda': {
  'nome': 'Solda e Consumíveis', 'icone': 'solda',
  'marcas': ['ESAB', 'Boxer', 'Western'],
  'linhas': [
   ('Inversoras', [130, 131, 132]),
   ('Inversoras MIG/MMA/TIG', [134, 135]),
   ('Corte Plasma', [137, 138]),
   ('Máscaras de Solda', [139, 140]),
   ('Eletrodos: Inox, 6013, 7018 e Tungstênio', [141, 142, 143]),
   ('Varetas de Solda', [144, 145, 146]),
   ('Arames MIG', [147]),
   ('Válvulas Corta-Chamas e Reguladores', [148, 149]),
   ('Porta Eletrodos e Grampos Terra', [150]),
   ('Consumíveis', [151]),
   ('Tochas MIG e TIG', [152, 153]),
   ('Mangueiras Duplas', [154]),
  ]},
 'pneumaticas': {
  'nome': 'Ferramentas Pneumáticas', 'icone': 'ar',
  'marcas': ['Chiaperini'],
  'linhas': [
   ('Furadeiras', [231]),
   ('Chaves de Impacto', [232]),
   ('Chaves Catraca', [233]),
   ('Microrretíficas', [234, 235]),
   ('Marteletes Rebarbadores', [236]),
   ('Esmerilhadeiras', [237]),
   ('Rebitadores', [238]),
   ('Lixadeiras', [239]),
   ('Grampeadores e Pregadores', [240, 241]),
  ]},
 'compressores': {
  'nome': 'Compressores', 'icone': 'compressor',
  'marcas': ['Chiaperini'],
  'linhas': [
   ('Ar Direto', [221]),
   ('Motocompressores', [222]),
   ('Compressores de Pistão', [223]),
   ('Compressores a Gasolina', [224]),
   ('Compressores Odontológicos', [225]),
   ('Óleos para Compressor', [226]),
   ('Filtros de Ar', [227, 228]),
   ('Pressostatos', [229]),
   ('Mangueiras Pneumáticas', [230]),
  ]},
 'pintura': {
  'nome': 'Equipamentos de Pintura', 'icone': 'pintura',
  'marcas': [],
  'linhas': [
   ('Airless', [212]),
   ('Pistolas Elétricas', [213]),
   ('Pistolas de Pintura', [214, 215, 216]),
   ('Filtros de Ar', [217, 218, 219]),
   ('Rolos, Bandejas, Trinchas e Mais', [220]),
  ]},
 'hidraulicos': {
  'nome': 'Equipamentos Hidráulicos', 'icone': 'macaco',
  'marcas': ['Bovenau'],
  'linhas': [
   ('Prensas Manuais', [189]),
   ('Guinchos Girafa', [190]),
   ('Macacos Hidráulicos', [191, 192]),
   ('Esticadores', [193]),
  ]},
 'cargas': {
  'nome': 'Movimentação de Cargas', 'icone': 'paleteira',
  'marcas': ['Bovenau'],
  'linhas': [
   ('Paleteiras', [164]),
   ('Empilhadeiras Manuais', [165]),
   ('Guinchos Coluna', [166]),
   ('Carrinhos Plataforma', [167]),
   ('Talhas Manuais e Troles', [168]),
  ]},
 'armazenamento': {
  'nome': 'Armazenamento e Organização', 'icone': 'caixa',
  'marcas': ['Metalcava', 'Ribeiro'],
  'linhas': [
   ('Caixas de Ferramentas', [170, 169, 171]),
   ('Organizadores', [172, 173]),
   ('Baús', [174, 175]),
   ('Mochilas e Bolsas', [176, 177]),
   ('Caixas Modulares', [178, 179, 180]),
   ('Carrinhos para Oficina', [181, 182]),
   ('Bancadas', [183, 184]),
   ('Rodízios', [185, 186, 187, 188]),
  ]},
 'lubrificacao': {
  'nome': 'Lubrificação', 'icone': 'oleo',
  'marcas': ['Lubefer'],
  'linhas': [
   ('Bombas Manuais para Graxa e Óleo', [194, 195]),
   ('Bombas Extratoras de Óleo', [196]),
   ('Bombas com Reservatório', [197, 198, 199]),
   ('Coletores de Óleo e Graxa', [200]),
  ]},
 'maquinas': {
  'nome': 'Máquinas e Equipamentos', 'icone': 'engrenagem',
  'marcas': ['Kawashima', 'Menegotti'],
  'linhas': [
   ('Furadeiras de Bancada', [201]),
   ('Serras de Bancada', [202]),
   ('Serras Fita', [203]),
   ('Geradores', [204]),
   ('Motobombas: Periférica, Caneta e Sapo', [205, 206, 207]),
   ('Moto-Esmeris', [208]),
   ('Transformadores', [209]),
   ('Eletrosserras', [210]),
   ('Plainas Desengrossadeiras', [211]),
  ]},
 'limpeza': {
  'nome': 'Equipamentos para Limpeza', 'icone': 'jato',
  'marcas': ['Kärcher'],
  'linhas': [
   ('Lavadoras', [343]),
   ('Lavadoras Industriais', [344, 345]),
   ('Lavadoras Lava-Jato', [346, 347]),
   ('Aspiradores Profissionais', [348, 349]),
  ]},
 'adesivos': {
  'nome': 'Adesivos e Químicos', 'icone': 'quimico',
  'marcas': ['Tekbond', 'WD-40', 'H7', 'Maxi Rubber'],
  'denso': True,
  'linhas': [
   ('Trava Roscas', [242]),
   ('Adesivos Instantâneos', [243]),
   ('Adesivos Titânio', [244]),
   ('Silicones', [245, 264]),
   ('Desengraxantes H7', [246]),
   ('Sabões Desengraxantes', [247]),
   ('Desengripantes', [248, 249]),
   ('Fluidos de Corte', [250]),
   ('Marcadores Industriais', [251]),
   ('Massas de Calafetar', [252]),
   ('Aguarrás', [253, 254]),
   ('Thinner', [255]),
   ('Querosene', [256]),
   ('Convertedores de Ferrugem', [257]),
   ('Óleos Solúveis', [258]),
   ('Colas de Contato', [259]),
   ('Descarbonizantes', [260]),
   ('Aceleradores', [261]),
   ('Limpa Contatos', [262]),
   ('Grafite', [263]),
   ('Massas Plásticas', [265]),
   ('Massas de Polir', [266]),
   ('Fibras de Vidro', [267]),
   ('Batidas de Pedra', [268]),
   ('Veda Choque', [269]),
   ('Vernizes', [270]),
   ('Graxas Líquidas', [271]),
   ('Vaselinas: Spray, Líquida e Pasta', [272, 273, 274]),
   ('Graxas Azul e Grafitada', [275, 276, 277, 278]),
   ('Removedores Pastosos', [279]),
   ('Vedadores de Capô', [280]),
   ('Espumas Expansivas', [281]),
   ('Chumbadores Químicos', [282]),
  ]},
 'fitas': {
  'nome': 'Fitas', 'icone': 'fita',
  'marcas': ['Adere', '3M', 'Tekbond'],
  'linhas': [
   ('Fitas Crepe', [283]),
   ('Crepe Automotiva', [284]),
   ('Fitas Isolantes', [285, 286, 287]),
   ('Demarcação de Solo', [288]),
   ('Empacotamento', [289]),
   ('Silver Tape', [290]),
   ('Dupla Face', [291, 292]),
   ('Aluminizadas', [293]),
   ('Fitas Impermeáveis', [294]),
   ('Fitas de Vedação', [295]),
  ]},
 'epi': {
  'nome': 'EPI e Segurança', 'icone': 'capacete',
  'marcas': ['Estival', 'Kadesh', 'EcoSafety', 'Sayro'],
  'chamada': 'Calçados de segurança Estival: linha completa de botinas, sapatos e botas PVC.',
  'linhas': [
   ('Sapatos, Botinas e Botas PVC', [301, 302, 303]),
   ('Luvas: Raspa, Vaqueta, PVC, Látex e Mais', [304, 305, 306, 307, 308, 309, 310, 311, 312]),
   ('Cintos de Segurança e Talabartes', [313]),
   ('Máscaras e Respiradores', [314, 315, 316, 317]),
   ('Filtros', [318, 319, 320]),
   ('Protetores Auditivos', [321, 322]),
   ('Óculos de Proteção', [323]),
   ('Capacetes', [324]),
   ('Protetores Faciais', [325]),
   ('Macacões de Proteção', [326]),
   ('Capas de Chuva', [327]),
   ('Aventais', [328, 329]),
   ('Macacões e Mangotes', [330, 331]),
   ('Protetores Solares', [332]),
  ]},
 'cadeados': {
  'nome': 'Cadeados, Correntes e Pedestais', 'icone': 'cadeado',
  'marcas': ['Pado', 'Stam'],
  'linhas': [
   ('Cadeados', [333, 334, 335]),
   ('Correntes', [336, 337]),
   ('Pedestais', [338]),
  ]},
 'jardinagem': {
  'nome': 'Jardinagem, Florestal e Agro', 'icone': 'folha',
  'marcas': ['Nakashi', 'Kawashima', 'Saints'],
  'linhas': [
   ('Aparadores de Grama Elétricos', [350, 351]),
   ('Cortadores a Gasolina', [352]),
   ('Roçadeiras a Gasolina', [353, 354]),
   ('Perfuradores de Solo', [355]),
   ('Motosserras', [356]),
   ('Sopradores a Gasolina', [357]),
   ('Microtratores', [358]),
   ('Mangueiras', [359, 360, 361]),
   ('Conectores e Bicos', [362]),
   ('Ferramentas para Jardim', [363, 364, 365]),
  ]},
 'construcao': {
  'nome': 'Construção Civil', 'icone': 'tijolo',
  'marcas': ['Menegotti', 'Cortag', 'Fercar'],
  'linhas': [
   ('Enxadas, Enxadões e Cavadeiras', [366, 367, 368]),
   ('Chibancas, Alviões, Alavancas e Pás', [369, 370, 371, 372]),
   ('Machados, Rastelos e Peneiras', [373, 374, 375, 376, 377]),
   ('Espátulas, Colheres e Talhadeiras', [378, 379, 380, 381]),
   ('Espumas, Caixas de Massa e Desempenadeiras', [382, 383, 384]),
   ('Carrinhos de Mão', [385, 386]),
   ('Compactadores de Solo', [387]),
   ('Betoneiras', [388]),
   ('Cortadores de Piso', [389, 390]),
   ('Cortadores de Bloco Manuais', [391]),
   ('Misturadores de Argamassa', [392]),
   ('Desempenadeiras Elétricas', [393]),
  ]},
 'ferragem': {
  'nome': 'Mecânica e Ferragem', 'icone': 'suporte',
  'marcas': ['Forsul', 'Hard'],
  'linhas': [
   ('Tornos e Eixos', [394, 395, 396]),
   ('Cantoneiras, Dobradiças e Ferrolhos', [397, 398, 399, 400, 401, 402, 403]),
   ('Abraçadeiras, Ganchos e Puxadores', [404, 405, 406, 407, 408]),
   ('Suportes', [409, 410, 411, 412, 413]),
  ]},
 'eletrica': {
  'nome': 'Elétrica', 'icone': 'raio',
  'marcas': ['Foxlux', 'Real'],
  'linhas': [
   ('Cabos: PP, Paralelo e Flexível', [414, 415, 416]),
   ('Lâmpadas', [417, 418, 419]),
   ('Disjuntores', [420]),
   ('Pinos Macho e Fêmea', [421]),
   ('Filtros de Linha e Extensões', [422, 423, 424]),
   ('Eletrificadores de Cerca', [425]),
   ('Luzes de Emergência e Lanternas', [426, 427, 428, 429]),
   ('Pilhas e Baterias', [430, 431]),
  ]},
}

# ------------------------------------------------- destaques especiais
VONIXX = {
 'titulo': 'Produtos Vonixx',
 'texto': 'Estética automotiva profissional: lava-autos, ceras, '
          'descontaminantes e acabamento. A linha completa Vonixx, '
          'pronta entrega na loja.',
 'fotos': [296],
}
TINTAS = {
 'titulo': 'Tintas e Acabamento',
 'chamadas': [
  ('Tintas Coral', 'Linha imobiliária pra sua obra', [297, 298]),
  ('Tintas Spray', 'Cores e usos variados', [299]),
  ('Corantes Xadrez', 'Pra personalizar a mistura', [300]),
 ],
}
ESCADAS = {
 'titulo': 'Escadas',
 'texto': 'De alumínio, fibra e aço, nas versões doméstica, extensiva e plataforma.',
 'marca': 'Botafogo',
 'fotos': [339, 340, 341, 342],
}
PARAFUSOS = {
 'titulo': 'Parafusos & Cabos de Aço',
 'kicker': 'A especialidade da casa',
 'texto': 'Da movelaria ao estrutural: bitola, rosca e acabamento para cada '
          'serviço. Se não estiver na prateleira, a gente busca.',
 'chips': ['Allen', 'Inox', 'Aço 8.8 e 10.9', 'Movelaria', 'Agrícola',
           'Industrial e Estrutural', 'Barra Roscada', 'Junções',
           'Chumbadores CBA e PBA'],
 'fixacao': [('Barra Roscada', [432]), ('Junções', [433]),
             ('Chumbador PBA', [434]), ('Chumbador CBA', [435])],
 'cabos': [('Cabos de Aço', [436]), ('Manilhas', [437]), ('Sapatilhas', [438]),
           ('Clips', [439]), ('Porcas Olhal', [440]), ('Parafusos Olhal', [441])],
 'marcas': ['Ciser', 'Jomarca', 'Robustec', 'Bremen'],
 'frase': 'Não achou a bitola? A gente tem.',
}

# ------------------------------------------------------------- marcas
MARCAS_PARCEIRAS = [
 'DeWalt', 'Starrett', 'ESAB', 'Kawashima', 'Western', 'Stanley', 'Cortag',
 'Boxer', 'Nakashi', 'Foxlux', 'Black+Decker', 'Chiaperini', 'Saints',
 'Robustec', 'Bremen', 'Makita', 'Bovenau', 'Minipa', 'Maxi Rubber',
 'Ribeiro', 'Vonder', '3M', 'Sata', 'H7', 'Denver', 'Menegotti', 'Adere',
 'Hansatécnica', 'Pinheiro', 'Real', 'CSM', 'Walter', 'Tramontina', 'Fercar',
 'Botafogo', 'EcoSafety', 'Pado', 'Gedore', 'WD-40', 'Servente', 'Estival',
 'Norton', 'Kärcher', 'Corneta', 'Brasforma', 'Kadesh', 'Tekbond', 'Jomarca',
 'Ciser', 'Belenus', 'Hard', 'Stam', 'Sayro', 'Fischer', 'Forsul',
 'Metalcava', 'CCM do Brasil', 'PDR', 'Lubefer', 'Vonixx', 'Coral', 'Xadrez',
]

# ------------------------------------------------------------ contato
CONTATO = {
 'fones': '(35) 3427-2450',
 'cidade': 'Pouso Alegre / MG',
 'entrega': 'Entrega grátis para Pouso Alegre e região',
 'entrega_obs': 'consulte condições com nossos especialistas',
}

# --------------------------------------------------------- paginação
# Cada página de seções: lista de ids. Especiais têm página própria.
PAGINAS = [
 ('capa', None),
 ('apresentacao', None),
 ('marcas', None),
 ('secoes', ['manuais']),
 ('secoes', ['corte', 'abrasivos']),
 ('secoes', ['bateria']),
 ('secoes', ['eletricas', 'medicao']),
 ('secoes', ['solda', 'pneumaticas']),
 ('secoes', ['compressores', 'pintura']),
 ('secoes', ['cargas', 'armazenamento', 'lubrificacao']),
 ('secoes', ['hidraulicos', 'maquinas', 'limpeza']),
 ('secoes', ['adesivos']),
 ('secoes', ['fitas', 'cadeados']),
 ('destaques', None),          # Vonixx + Tintas + Escadas
 ('secoes', ['epi']),
 ('secoes', ['jardinagem', 'eletrica']),
 ('secoes', ['construcao', 'ferragem']),
 ('parafusos', None),
 ('contracapa', None),
]
